name: 发布到NPM

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 设置Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 指定Node.js版本
          registry-url: https://registry.npmjs.org/

      - name: 依赖安装
        run: yarn install

      - name: 项目打包
        run: yarn build

      - name: 发布到NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 创建GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true # 自动生成版本发布说明
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
